/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenlab2_jamilgarcia;

import java.awt.Panel;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JamilGarcía
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        jPanel1.setVisible(false);
        DefaultComboBoxModel atms = (DefaultComboBoxModel) cb_ATMs.getModel();
        ArrayList<ATM> listaATMs = new ArrayList();
        AdminATM adat = new AdminATM("./ATMs.jg");
        adat.cargarArchivo();
        listaATMs = adat.getListaAtm();
        for (int i = 0; i < listaATMs.size(); i++) {
            atms.addElement(listaATMs.get(i).getID_ATM());
        }
        cb_ATMs.setModel(atms);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_Cliente = new javax.swing.JFrame();
        cb_Cliente_cuentas = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        b_Cliente_CrearCuenta = new javax.swing.JButton();
        b_Cliente_Retirar = new javax.swing.JButton();
        b_Cliente_Ingresar = new javax.swing.JButton();
        b_Cliente_Depositar = new javax.swing.JButton();
        b_Cliente_Estado = new javax.swing.JButton();
        b_Cliente_Transacciones = new javax.swing.JButton();
        jf_Mantenimiento = new javax.swing.JFrame();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        sp_mantenimiento_100 = new javax.swing.JSpinner();
        sp_mantenimiento_500 = new javax.swing.JSpinner();
        b_Mantenimiento_Ingresar = new javax.swing.JButton();
        jf_Registrarse = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_register_nombre1 = new javax.swing.JTextField();
        tf_register_nombre2 = new javax.swing.JTextField();
        tf_register_apellido1 = new javax.swing.JTextField();
        tf_register_apellido2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_register_contra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_register_ANacimiento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_register_AAfiliacion = new javax.swing.JTextField();
        b_registrarse_Cliente = new javax.swing.JButton();
        b_register_mantenimiento = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tf_register_id = new javax.swing.JTextField();
        jf_CrearATM = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_CrearATM_Ubicacion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_CrearATM_ID = new javax.swing.JTextField();
        tf_CrearATM_AFab = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_CrearATM_Tman = new javax.swing.JFormattedTextField();
        b_CrearATM_Crear = new javax.swing.JButton();
        jf_Cliente_Depositar = new javax.swing.JFrame();
        jLabel20 = new javax.swing.JLabel();
        cb_Cliente_ID = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        sp_Cliente_Cantidad = new javax.swing.JSpinner();
        b_cliente_depositar = new javax.swing.JButton();
        jf_transacciones = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaTransacciones = new javax.swing.JList<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_ATMs = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        b_login_registrarse = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_login_ID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_login_contra = new javax.swing.JTextField();
        b_login_Cliente = new javax.swing.JButton();
        b_login_mantenimiento = new javax.swing.JButton();
        b_CrearATM = new javax.swing.JButton();

        cb_Cliente_cuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_Cliente_cuentasActionPerformed(evt);
            }
        });

        jLabel19.setText("Cuentas:");

        b_Cliente_CrearCuenta.setText("Crear Cuenta");
        b_Cliente_CrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_Cliente_CrearCuentaMouseClicked(evt);
            }
        });

        b_Cliente_Retirar.setText("Retirar Dinero");
        b_Cliente_Retirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_Cliente_RetirarMouseClicked(evt);
            }
        });

        b_Cliente_Ingresar.setText("Ingresar Dinero");
        b_Cliente_Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_Cliente_IngresarMouseClicked(evt);
            }
        });

        b_Cliente_Depositar.setText("Depositar Dinero a Otra Cuenta");
        b_Cliente_Depositar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_Cliente_DepositarMouseClicked(evt);
            }
        });

        b_Cliente_Estado.setText("Estado De Cuenta");
        b_Cliente_Estado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_Cliente_EstadoMouseClicked(evt);
            }
        });

        b_Cliente_Transacciones.setText("Transacciones");
        b_Cliente_Transacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_Cliente_TransaccionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_ClienteLayout = new javax.swing.GroupLayout(jf_Cliente.getContentPane());
        jf_Cliente.getContentPane().setLayout(jf_ClienteLayout);
        jf_ClienteLayout.setHorizontalGroup(
            jf_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_ClienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jf_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_ClienteLayout.createSequentialGroup()
                        .addGroup(jf_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_Cliente_Transacciones)
                            .addComponent(b_Cliente_Estado)
                            .addComponent(b_Cliente_Depositar)
                            .addGroup(jf_ClienteLayout.createSequentialGroup()
                                .addComponent(cb_Cliente_cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(b_Cliente_CrearCuenta))
                            .addComponent(jLabel19))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jf_ClienteLayout.createSequentialGroup()
                        .addGroup(jf_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_Cliente_Ingresar)
                            .addComponent(b_Cliente_Retirar))
                        .addGap(229, 684, Short.MAX_VALUE))))
        );
        jf_ClienteLayout.setVerticalGroup(
            jf_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_ClienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jf_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_Cliente_CrearCuenta)
                    .addGroup(jf_ClienteLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(cb_Cliente_cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(b_Cliente_Retirar)
                .addGap(41, 41, 41)
                .addComponent(b_Cliente_Ingresar)
                .addGap(53, 53, 53)
                .addComponent(b_Cliente_Depositar)
                .addGap(52, 52, 52)
                .addComponent(b_Cliente_Estado)
                .addGap(59, 59, 59)
                .addComponent(b_Cliente_Transacciones)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLabel23.setText("Ingrese la cantidad de Billetes Ingresados:");

        jLabel24.setText("Billetes De 100:");

        jLabel25.setText("Billetes De 500:");

        b_Mantenimiento_Ingresar.setText("Ingresar");
        b_Mantenimiento_Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_Mantenimiento_IngresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_MantenimientoLayout = new javax.swing.GroupLayout(jf_Mantenimiento.getContentPane());
        jf_Mantenimiento.getContentPane().setLayout(jf_MantenimientoLayout);
        jf_MantenimientoLayout.setHorizontalGroup(
            jf_MantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_MantenimientoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jf_MantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jf_MantenimientoLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(sp_mantenimiento_100))
                    .addComponent(jLabel23)
                    .addGroup(jf_MantenimientoLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addGroup(jf_MantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_Mantenimiento_Ingresar)
                            .addComponent(sp_mantenimiento_500))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jf_MantenimientoLayout.setVerticalGroup(
            jf_MantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_MantenimientoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel23)
                .addGap(48, 48, 48)
                .addGroup(jf_MantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(sp_mantenimiento_100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jf_MantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(sp_mantenimiento_500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(b_Mantenimiento_Ingresar)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jf_Registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jf_RegistrarseMouseClicked(evt);
            }
        });

        jLabel8.setText("Registrarse");

        jLabel9.setText("Primer Nombre:");

        jLabel10.setText("Segundo Nombre:");

        jLabel11.setText("Primer Apeliido:");

        jLabel12.setText("Segundo Apellido:");

        jLabel1.setText("Contraseña:");

        jLabel2.setText("Año De Nacimiento:");

        jLabel3.setText("Año De Afiliacion:");

        b_registrarse_Cliente.setText("Registrarse Como Cliente");
        b_registrarse_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_registrarse_ClienteMouseClicked(evt);
            }
        });

        b_register_mantenimiento.setText("Registrarse Como Mantenimiento");
        b_register_mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_register_mantenimientoMouseClicked(evt);
            }
        });

        jLabel13.setText("ID:");

        tf_register_id.setEditable(false);

        javax.swing.GroupLayout jf_RegistrarseLayout = new javax.swing.GroupLayout(jf_Registrarse.getContentPane());
        jf_Registrarse.getContentPane().setLayout(jf_RegistrarseLayout);
        jf_RegistrarseLayout.setHorizontalGroup(
            jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_RegistrarseLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_RegistrarseLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jf_RegistrarseLayout.createSequentialGroup()
                        .addGroup(jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13))
                        .addGap(28, 28, 28)
                        .addGroup(jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_register_nombre1)
                            .addComponent(tf_register_nombre2)
                            .addComponent(tf_register_apellido1)
                            .addComponent(tf_register_apellido2)
                            .addComponent(tf_register_contra)
                            .addComponent(tf_register_ANacimiento)
                            .addComponent(tf_register_AAfiliacion)
                            .addComponent(tf_register_id, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_registrarse_Cliente)
                            .addComponent(b_register_mantenimiento))
                        .addGap(33, 33, 33))))
        );
        jf_RegistrarseLayout.setVerticalGroup(
            jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_RegistrarseLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addGroup(jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(tf_register_id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_register_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_register_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_registrarse_Cliente))
                .addGap(20, 20, 20)
                .addGroup(jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_register_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_register_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_register_mantenimiento))
                .addGap(27, 27, 27)
                .addGroup(jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_register_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_register_ANacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jf_RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_register_AAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jLabel14.setText("Crear ATM");

        jLabel15.setText("Ubicacion:");

        jLabel16.setText("Año De Fab");

        jLabel17.setText("ID:");

        tf_CrearATM_ID.setEditable(false);

        jLabel18.setText("Tiempo Man (min):");

        tf_CrearATM_Tman.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));

        b_CrearATM_Crear.setText("Crear");
        b_CrearATM_Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_CrearATM_CrearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_CrearATMLayout = new javax.swing.GroupLayout(jf_CrearATM.getContentPane());
        jf_CrearATM.getContentPane().setLayout(jf_CrearATMLayout);
        jf_CrearATMLayout.setHorizontalGroup(
            jf_CrearATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_CrearATMLayout.createSequentialGroup()
                .addGroup(jf_CrearATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jf_CrearATMLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b_CrearATM_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jf_CrearATMLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jf_CrearATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jf_CrearATMLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(tf_CrearATM_Tman, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addComponent(jLabel14)
                            .addGroup(jf_CrearATMLayout.createSequentialGroup()
                                .addGroup(jf_CrearATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addGap(35, 35, 35)
                                .addGroup(jf_CrearATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_CrearATM_Ubicacion)
                                    .addComponent(tf_CrearATM_ID)
                                    .addComponent(tf_CrearATM_AFab, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jf_CrearATMLayout.setVerticalGroup(
            jf_CrearATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_CrearATMLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addGap(22, 22, 22)
                .addGroup(jf_CrearATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_CrearATM_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jf_CrearATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_CrearATM_Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jf_CrearATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_CrearATMLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jf_CrearATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tf_CrearATM_Tman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jf_CrearATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_CrearATM_AFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addGap(81, 81, 81)
                .addComponent(b_CrearATM_Crear)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel20.setText("Depositar");

        jLabel21.setText("Cuenta A Depositar:");

        jLabel22.setText("Cantidad A Depositar");

        b_cliente_depositar.setText("Depositar");
        b_cliente_depositar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_cliente_depositarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_Cliente_DepositarLayout = new javax.swing.GroupLayout(jf_Cliente_Depositar.getContentPane());
        jf_Cliente_Depositar.getContentPane().setLayout(jf_Cliente_DepositarLayout);
        jf_Cliente_DepositarLayout.setHorizontalGroup(
            jf_Cliente_DepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_Cliente_DepositarLayout.createSequentialGroup()
                .addGroup(jf_Cliente_DepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_Cliente_DepositarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jf_Cliente_DepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp_Cliente_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(cb_Cliente_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(jf_Cliente_DepositarLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(b_cliente_depositar)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jf_Cliente_DepositarLayout.setVerticalGroup(
            jf_Cliente_DepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_Cliente_DepositarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(cb_Cliente_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel22)
                .addGap(33, 33, 33)
                .addComponent(sp_Cliente_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(b_cliente_depositar)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        ListaTransacciones.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(ListaTransacciones);

        jLabel26.setText("Transacciones");

        javax.swing.GroupLayout jf_transaccionesLayout = new javax.swing.GroupLayout(jf_transacciones.getContentPane());
        jf_transacciones.getContentPane().setLayout(jf_transaccionesLayout);
        jf_transaccionesLayout.setHorizontalGroup(
            jf_transaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_transaccionesLayout.createSequentialGroup()
                .addGroup(jf_transaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_transaccionesLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel26))
                    .addGroup(jf_transaccionesLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jf_transaccionesLayout.setVerticalGroup(
            jf_transaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_transaccionesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel26)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Seleccione Un Cajero:");

        cb_ATMs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ATMsItemStateChanged(evt);
            }
        });

        b_login_registrarse.setText("Registrarse");
        b_login_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_login_registrarseMouseClicked(evt);
            }
        });

        jLabel5.setText("Login");

        jLabel6.setText("ID:");

        jLabel7.setText("Contraseña:");

        b_login_Cliente.setText("Login Como Cliente");
        b_login_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_login_ClienteMouseClicked(evt);
            }
        });

        b_login_mantenimiento.setText("Login Como Mantenimiento");
        b_login_mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_login_mantenimientoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_login_registrarse)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_login_mantenimiento)
                            .addComponent(b_login_Cliente)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_login_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_login_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 363, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_login_registrarse)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_login_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_login_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(67, 67, 67)
                .addComponent(b_login_Cliente)
                .addGap(44, 44, 44)
                .addComponent(b_login_mantenimiento)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        b_CrearATM.setText("Crear ATM");
        b_CrearATM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_CrearATMMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(cb_ATMs, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_ATMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_CrearATM))
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_login_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_login_ClienteMouseClicked
        // TODO add your handling code here:
        
        ArrayList<Cliente> client = new ArrayList();
        AdminCliente adcl = new AdminCliente("./clientes.jg");
        adcl.cargarArchivo();
        client = adcl.getListaCliente();
        int id = Integer.parseInt(tf_login_ID.getText());
        String contra = tf_login_contra.getText();

        for (int i = 0; i < client.size(); i++) {
            if (id == client.get(i).getID_U()) {
                if (contra.equals(client.get(i).getContra())) {
                    jf_Cliente.setVisible(true);
                    JOptionPane.showMessageDialog(this, "Bienvenido!!!");
                    ID_ACTIVO = id;
                    ATM_ACTIVO = cb_ATMs.getSelectedIndex();
                    Num_Usuario = i;
                    System.out.println(ID_ACTIVO);
                    DefaultComboBoxModel cuen = (DefaultComboBoxModel) cb_Cliente_cuentas.getModel();
                    for (int j = 0; j < client.get(i).getCuentas().size(); j++) {
                        cuen.addElement(client.get(i).getCuentas().get(j));
                    }
                    cb_Cliente_cuentas.setModel(cuen);
                    try {
                        log(ID_ACTIVO, "Se logeó como cliente");
                    } catch (IOException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_b_login_ClienteMouseClicked

    private void cb_ATMsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ATMsItemStateChanged
        // TODO add your handling code here:
        jPanel1.setVisible(true);
    }//GEN-LAST:event_cb_ATMsItemStateChanged

    private void b_login_mantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_login_mantenimientoMouseClicked
        // TODO add your handling code here:
        ArrayList<Mantenimiento> mant = new ArrayList();
        AdminMantenimiento admn = new AdminMantenimiento("./mantenimiento.jg");
        admn.cargarArchivo();
        mant = admn.getListaMantenimiento();
        int id = Integer.parseInt(tf_login_ID.getText());
        String contra = tf_login_contra.getText();

        for (int i = 0; i < mant.size(); i++) {
            if (id == mant.get(i).getID_U()) {
                if (contra.equals(mant.get(i).getContra())) {
                    jf_Mantenimiento.setVisible(true);
                    ID_ATM = cb_ATMs.getSelectedIndex();
                    ID_ACTIVO = id;
                    Num_Usuario = i;
                    try {
                        log(ID_ACTIVO, "Se logeó como mantenimiento");
                    } catch (IOException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_b_login_mantenimientoMouseClicked

    private void b_login_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_login_registrarseMouseClicked
        // TODO add your handling code here:
        jf_Registrarse.setVisible(true);
        int temp = 100000 + ran.nextInt(300000);
        tf_register_id.setText(Integer.toString(temp));
    }//GEN-LAST:event_b_login_registrarseMouseClicked

    private void b_registrarse_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_registrarse_ClienteMouseClicked
        // TODO add your handling code here:
        try {
            String nombre1, nombre2, apellido1, apellido2, contra;
            int id, a_naci, a_afil;

            id = Integer.parseInt(tf_register_id.getText());
            nombre1 = tf_register_nombre1.getText();
            nombre2 = tf_register_nombre2.getText();
            apellido1 = tf_register_apellido1.getText();
            apellido2 = tf_register_apellido2.getText();
            contra = tf_register_contra.getText();
            a_naci = Integer.parseInt(tf_register_ANacimiento.getText());
            a_afil = Integer.parseInt(tf_register_AAfiliacion.getText());
            Cliente c = new Cliente(id, nombre1, nombre2, apellido1, apellido2, contra, a_naci, a_afil);
            AdminCliente adcl = new AdminCliente("./clientes.jg");
            adcl.cargarArchivo();
            adcl.setCliente(c);
            adcl.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Añadido con Exito");
            jf_Registrarse.dispose();
            log(id, "Fue Creado");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_b_registrarse_ClienteMouseClicked

    private void b_register_mantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_register_mantenimientoMouseClicked
        // TODO add your handling code here:
        try {
            String nombre1, nombre2, apellido1, apellido2, contra;
            int id, a_naci, a_afil;

            id = Integer.parseInt(tf_register_id.getText());
            nombre1 = tf_register_nombre1.getText();
            nombre2 = tf_register_nombre2.getText();
            apellido1 = tf_register_apellido1.getText();
            apellido2 = tf_register_apellido2.getText();
            contra = tf_register_contra.getText();
            a_naci = Integer.parseInt(tf_register_ANacimiento.getText());
            a_afil = Integer.parseInt(tf_register_AAfiliacion.getText());

            Mantenimiento m = new Mantenimiento(id, nombre1, nombre2, apellido1, apellido2, contra, a_naci, a_afil);
            AdminMantenimiento admn = new AdminMantenimiento("./mantenimiento.jg");
            admn.cargarArchivo();
            admn.setMantenimiento(m);
            admn.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Añadido con Exito");
            jf_Registrarse.dispose();
            adat.cargarArchivo();
            ArrayList<ATM> listaAtms = new ArrayList();
            ArrayList<ATM> listaAtms2 = new ArrayList();
            listaAtms = adat.getListaAtm();
            admn.cargarArchivo();
            int temp;
            for (int i = 0; i < 3; i++) {
                temp = ran.nextInt(listaAtms.size());
                listaAtms2.add(listaAtms.get(temp));
                adat.setAtm(listaAtms2.get(i));
            }
            adat.escribirArchivo();
            log(id, "Fue creado");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_b_register_mantenimientoMouseClicked

    private void b_CrearATMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_CrearATMMouseClicked
        // TODO add your handling code here:
        jf_CrearATM.setVisible(true);
        int temp = 400000 + ran.nextInt(200000);
        tf_CrearATM_ID.setText(Integer.toString(temp));
    }//GEN-LAST:event_b_CrearATMMouseClicked

    private void b_CrearATM_CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_CrearATM_CrearMouseClicked
        // TODO add your handling code here:
        try {
            String tman, ubicacion;
            int id, a_fab;

            id = Integer.parseInt(tf_CrearATM_ID.getText());
            ubicacion = tf_CrearATM_Ubicacion.getText();
            a_fab = Integer.parseInt(tf_CrearATM_AFab.getText());
            tman = tf_CrearATM_Tman.getText();
            ATM a = new ATM(0, ubicacion, id, a_fab, tman);
            AdminATM adat = new AdminATM("./ATMs.jg");
            adat.cargarArchivo();
            adat.setAtm(a);
            adat.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Creado Con Exito, reinicie para ver los cambios");
            jf_CrearATM.dispose();
            log(0, "Alguien creo un ATM");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_b_CrearATM_CrearMouseClicked

    private void cb_Cliente_cuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_Cliente_cuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_Cliente_cuentasActionPerformed

    private void b_Cliente_CrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_Cliente_CrearCuentaMouseClicked
        // TODO add your handling code here:
        AdminCliente adcl = new AdminCliente("./clientes.jg");
        ArrayList<Cuentas> listaCuentas = new ArrayList();
        adcl.cargarArchivo();
        int NumCuen, saldo, ID_U;
        int temp = 600000 + ran.nextInt(200000);
        NumCuen = temp;
        saldo = 0;
        ID_U = ID_ACTIVO;
        Cuentas c = new Cuentas(NumCuen, saldo, ID_U);
        adcl.getListaCliente().get(Num_Usuario).getCuentas().add(c);
        adcl.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Cuenta Creada Con Exito \n"
                + "Numero De Cuenta: " + NumCuen + "\n"
                + "Saldo: " + saldo + "\n"
                + "ID De Usuario: " + ID_U);
        ArrayList<Cliente> client = new ArrayList();
        adcl.cargarArchivo();
        client = adcl.getListaCliente();
        DefaultComboBoxModel cuen = (DefaultComboBoxModel) cb_Cliente_cuentas.getModel();
        for (int j = 0; j < client.get(Num_Usuario).getCuentas().size(); j++) {
            cuen.addElement(client.get(Num_Usuario).getCuentas().get(j));
        }
        cb_Cliente_cuentas.setModel(cuen);
        try {
            log(ID_ACTIVO, "Creó una nueva cuenta");
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_b_Cliente_CrearCuentaMouseClicked

    private void b_Cliente_RetirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_Cliente_RetirarMouseClicked
        // TODO add your handling code here:
        int temp = cb_Cliente_cuentas.getSelectedIndex();
        String ID_c = cb_Cliente_cuentas.getSelectedItem().toString();
        Date fecha = new Date();
        int temp2 = 800000 + ran.nextInt(1000000);

        int dinero = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la cantidad de dinero a retirar: "));
        adcl.cargarArchivo();
        int dinerodisp = adcl.getListaCliente().get(Num_Usuario).getCuentas().get(temp).getSaldo();
        AdminATM adat = new AdminATM("./ATMs.jg");
        adat.cargarArchivo();
        int dineroATM = adat.getListaAtm().get(ATM_ACTIVO).getDinero();
        if (dineroATM > dinero) {
            if (dinero <= dinerodisp) {
                dinerodisp -= dinero;
                dineroATM -= dinero;
                adat.getListaAtm().get(ATM_ACTIVO).setDinero(dineroATM);
                adat.escribirArchivo();
                adcl.getListaCliente().get(Num_Usuario).getCuentas().get(temp).setSaldo(dinerodisp);
                adcl.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Retirado con Exito");
                jf_Cliente.dispose();

                adtr.cargarArchivo();
                adcl.cargarArchivo();
                ArrayList<Transacciones> listatr = new ArrayList();
                listatr.add(new Transacciones(ID_c, "Se Retiró Dinero: ", fecha, temp2));
                adcl.getListaCliente().get(Num_Usuario).setTrans(listatr);
                adcl.escribirArchivo();

                try {
                    log(ID_ACTIVO, "Retiró Dinero");
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No hay Suficiente dinero en la cuenta");
                try {
                    log(ID_ACTIVO, "Le falló por falta de Dinero");
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay Suficiente dinero en el cajero");
            try {
                log(ID_ACTIVO, "Le falló el ATM");
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_b_Cliente_RetirarMouseClicked

    private void b_Cliente_IngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_Cliente_IngresarMouseClicked
        // TODO add your handling code here:
        int temp = cb_Cliente_cuentas.getSelectedIndex();
        String ID_c = cb_Cliente_cuentas.getSelectedItem().toString();
        Date fecha = new Date();
        int temp2 = 800000 + ran.nextInt(1000000);

        int dinero = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la cantidad de dinero a ingresar: "));
        adcl.cargarArchivo();
        adat.cargarArchivo();
        int dinerodisp = adcl.getListaCliente().get(Num_Usuario).getCuentas().get(temp).getSaldo();
        int dineroATM = adat.getListaAtm().get(ATM_ACTIVO).getDinero();
        dinerodisp += dinero;
        dineroATM += dinero;
        adat.getListaAtm().get(ATM_ACTIVO).setDinero(dineroATM);
        adat.escribirArchivo();
        adcl.getListaCliente().get(Num_Usuario).getCuentas().get(temp).setSaldo(dinerodisp);
        adcl.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Sea Ingresado con exito");
        jf_Cliente.dispose();
        adtr.cargarArchivo();
        adcl.cargarArchivo();
        ArrayList<Transacciones> listatr = new ArrayList();
        listatr.add(new Transacciones(ID_c, "Se Ingresó Dinero: ", fecha, temp2));
        adcl.getListaCliente().get(Num_Usuario).setTrans(listatr);
        adcl.escribirArchivo();
        try {
            log(ID_ACTIVO, "Ingresó dinero a su cuenta");
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_Cliente_IngresarMouseClicked

    private void b_Cliente_DepositarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_Cliente_DepositarMouseClicked
        // TODO add your handling code here:

        jf_Cliente_Depositar.setVisible(true);
        DefaultComboBoxModel cuen = (DefaultComboBoxModel) cb_Cliente_cuentas.getModel();
        ArrayList<Cliente> client = new ArrayList();
        adcl.cargarArchivo();
        client = adcl.getListaCliente();
        for (int i = 0; i < client.size(); i++) {
            for (int j = 0; j < client.get(i).getCuentas().size(); j++) {
                cuen.addElement(client.get(i).getCuentas().get(j));
            }
        }
        cb_Cliente_cuentas.setModel(cuen);


    }//GEN-LAST:event_b_Cliente_DepositarMouseClicked

    private void b_cliente_depositarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cliente_depositarMouseClicked
        // TODO add your handling code here:
        int temp = cb_Cliente_cuentas.getSelectedIndex();
        String ID_c = cb_Cliente_cuentas.getSelectedItem().toString();
        Date fecha = new Date();
        int temp2 = 800000 + ran.nextInt(1000000);
        ArrayList<Cliente> client = new ArrayList();
        adcl.cargarArchivo();
        client = adcl.getListaCliente();
        int index = cb_Cliente_cuentas.getSelectedIndex();
        
        int dinerodisp = adcl.getListaCliente().get(Num_Usuario).getCuentas().get(temp).getSaldo();
        int dineroCuenEx = adcl.getListaCliente().get(Num_Usuario).getCuentas().get(index).getSaldo();
        int dinero = sp_Cliente_Cantidad.getComponentCount();
        dinerodisp -= dinero;
        dineroCuenEx += dinero;
        adcl.getListaCliente().get(Num_Usuario).getCuentas().get(temp).setSaldo(dinerodisp);
        adcl.getListaCliente().get(Num_Usuario).getCuentas().get(index).setSaldo(dineroCuenEx);
        JOptionPane.showMessageDialog(this, "Depositado con exito");
        jf_Cliente.dispose();
        jf_Cliente_Depositar.dispose();
        adtr.cargarArchivo();
        adcl.cargarArchivo();
        ArrayList<Transacciones> listatr = new ArrayList();
        listatr.add(new Transacciones(ID_c, "Se Ingresó Dinero: ", fecha, temp2));
        adcl.getListaCliente().get(Num_Usuario).setTrans(listatr);
        adcl.escribirArchivo();
        try {
            log(ID_ACTIVO, "Depositó dinero a otra cuenta");
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_cliente_depositarMouseClicked

    private void b_Cliente_EstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_Cliente_EstadoMouseClicked
        // TODO add your handling code here:
        int temp = cb_Cliente_cuentas.getSelectedIndex();
        int Num_Cuenta = adcl.getListaCliente().get(Num_Usuario).getCuentas().get(temp).getNumCuen();
        int dinerodisp = adcl.getListaCliente().get(Num_Usuario).getCuentas().get(temp).getSaldo();
        JOptionPane.showMessageDialog(this, "Numero De Cuenta: " + Num_Cuenta + "\n"
                + "ID Usuario: " + ID_ACTIVO + "\n"
                + "Dinero disponible: " + dinerodisp);
        try {
            log(ID_ACTIVO, "Vió su estado de cuenta");
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_b_Cliente_EstadoMouseClicked

    private void jf_RegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jf_RegistrarseMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jf_RegistrarseMouseClicked

    private void b_Mantenimiento_IngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_Mantenimiento_IngresarMouseClicked
        // TODO add your handling code here:
        boolean t = true;
        admn.cargarArchivo();

        for (int i = 0; i < admn.getListaMantenimiento().get(Num_Usuario).getAtm().size(); i++) {
            if (ID_ATM != admn.getListaMantenimiento().get(Num_Usuario).getAtm().get(i).getID_ATM()) {
                t = false;
            }
        }

        if (t) {
            String pass = JOptionPane.showInputDialog(this, "Ingrese la contraseña para cerrar");
            if (pass.equals(admn.getListaMantenimiento().get(Num_Usuario).getContra())) {
                int dinero1 = sp_mantenimiento_100.getComponentCount() * 100;
                int dinero2 = sp_mantenimiento_500.getComponentCount() * 500;
                adat.cargarArchivo();
                int temp = cb_ATMs.getSelectedIndex();
                int dineroATM = adat.getListaAtm().get(temp).getDinero();
                dineroATM += dinero1 + dinero2;
                adat.getListaAtm().get(temp).setDinero(dineroATM);
                try {
                    log(ID_ACTIVO, "Ingresó dinero al ATM");
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error!!! NO TIENES PERMISO PARA USAR ESTE ATM");
            try {
                log(ID_ACTIVO, "Intentó ingresar a un ATM incorrecto");
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_b_Mantenimiento_IngresarMouseClicked

    private void b_Cliente_TransaccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_Cliente_TransaccionesMouseClicked
        // TODO add your handling code here:
        jf_transacciones.setVisible(true);
        DefaultListModel listaM = (DefaultListModel) ListaTransacciones.getModel();
        adcl.cargarArchivo();
        ArrayList <Transacciones> listatr = new ArrayList();
        listatr = adcl.getListaCliente().get(Num_Usuario).getTrans();
        for (int i = 0; i < listatr.size(); i++) {
            listaM.addElement(listatr.get(i));
        }
        ListaTransacciones.setModel(listaM);
    }//GEN-LAST:event_b_Cliente_TransaccionesMouseClicked

  

    public void log(int id, String accion) throws IOException {
        Date fecha = new Date();
        File f = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            f = new File("./log.txt");
            fw = new FileWriter(f, true); //OJO 
            bw = new BufferedWriter(fw);
            bw.write("El ID: " + id + " " + accion + " justo a las: " + fecha  + "   ;   ");
            bw.flush();

        } catch (Exception e) {
            e.printStackTrace();
        }
        bw.close();
        fw.close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaTransacciones;
    private javax.swing.JButton b_Cliente_CrearCuenta;
    private javax.swing.JButton b_Cliente_Depositar;
    private javax.swing.JButton b_Cliente_Estado;
    private javax.swing.JButton b_Cliente_Ingresar;
    private javax.swing.JButton b_Cliente_Retirar;
    private javax.swing.JButton b_Cliente_Transacciones;
    private javax.swing.JButton b_CrearATM;
    private javax.swing.JButton b_CrearATM_Crear;
    private javax.swing.JButton b_Mantenimiento_Ingresar;
    private javax.swing.JButton b_cliente_depositar;
    private javax.swing.JButton b_login_Cliente;
    private javax.swing.JButton b_login_mantenimiento;
    private javax.swing.JButton b_login_registrarse;
    private javax.swing.JButton b_register_mantenimiento;
    private javax.swing.JButton b_registrarse_Cliente;
    private javax.swing.JComboBox<String> cb_ATMs;
    private javax.swing.JComboBox<String> cb_Cliente_ID;
    private javax.swing.JComboBox<String> cb_Cliente_cuentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFrame jf_Cliente;
    private javax.swing.JFrame jf_Cliente_Depositar;
    private javax.swing.JFrame jf_CrearATM;
    private javax.swing.JFrame jf_Mantenimiento;
    private javax.swing.JFrame jf_Registrarse;
    private javax.swing.JFrame jf_transacciones;
    private javax.swing.JSpinner sp_Cliente_Cantidad;
    private javax.swing.JSpinner sp_mantenimiento_100;
    private javax.swing.JSpinner sp_mantenimiento_500;
    private javax.swing.JTextField tf_CrearATM_AFab;
    private javax.swing.JTextField tf_CrearATM_ID;
    private javax.swing.JFormattedTextField tf_CrearATM_Tman;
    private javax.swing.JTextField tf_CrearATM_Ubicacion;
    private javax.swing.JTextField tf_login_ID;
    private javax.swing.JTextField tf_login_contra;
    private javax.swing.JTextField tf_register_AAfiliacion;
    private javax.swing.JTextField tf_register_ANacimiento;
    private javax.swing.JTextField tf_register_apellido1;
    private javax.swing.JTextField tf_register_apellido2;
    private javax.swing.JTextField tf_register_contra;
    private javax.swing.JTextField tf_register_id;
    private javax.swing.JTextField tf_register_nombre1;
    private javax.swing.JTextField tf_register_nombre2;
    // End of variables declaration//GEN-END:variables
    Random ran = new Random();
    int ID_ACTIVO, Num_Usuario, ATM_ACTIVO, ID_ATM, ID_Cuenta;
    AdminATM adat = new AdminATM("./ATMs.jg");
    AdminCliente adcl = new AdminCliente("./clientes.jg");
    AdminMantenimiento admn = new AdminMantenimiento("./mantenimiento.jg");
    AdminTransacciones adtr = new AdminTransacciones("./transaccion.jg");

}
